name: "little-penguin"

services:
  dev-container:
    image: little-penguin-dev:latest
    build:
      context: .
      dockerfile: .devcontainer/src/dev-container/Dockerfile
    command: sleep infinity
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - .:/ws
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/kvm:/dev/kvm
    security_opt:
      - seccomp=unconfined
    cap_add:
      - ALL
    network_mode: "bridge"
